const path = require('node:path');
module.exports = async ({ run, appDir }) => {
  const api = require(path.join(appDir, 'controllers/api'));
  const user = (kind, extra = {}) => ({ user: { tokens: [{ kind, accessToken: 'AT', tokenSecret: 'TS', refreshToken: 'RT' }], profile: { name: 'Ann' }, ...extra } });
  await run('getApi', api, 'getApi');
  await run('foursquare ok', api, 'getFoursquare', {}, { 'places/search': { body: { results: [{ a: 1 }] } }, 'places/427': { body: { name: 'v' } } });
  await run('foursquare ok no results', api, 'getFoursquare', {}, { 'places/search': { body: {} }, 'places/427': { body: { name: 'v' } } });
  await run('foursquare fail', api, 'getFoursquare', {}, { 'places/search': { status: 500, statusText: 'ISE', body: 'boom' }, 'places/427': { body: { name: 'v' } } });
  await run('tumblr ok', api, 'getTumblr', user('tumblr'), { 'user/info': { body: { response: { user: { name: 'u' } } } }, '/posts/': { body: { response: { blog: { b: 1 }, posts: [{ photos: [1, 2] }] } } } });
  await run('tumblr userinfo fail', api, 'getTumblr', user('tumblr'), { 'user/info': { status: 401, body: {} } });
  await run('tumblr blog fail', api, 'getTumblr', user('tumblr'), { 'user/info': { body: { response: { user: {} } } }, '/posts/': { status: 500, body: {} } });
  await run('tumblr no token', api, 'getTumblr', user('x'));
  await run('facebook ok', api, 'getFacebook', user('facebook', { facebook: '123' }), { 'graph.facebook.com': { body: { id: 1, name: 'n' } } });
  await run('facebook fail msg', api, 'getFacebook', user('facebook', { facebook: '123' }), { 'graph.facebook.com': { status: 400, body: { message: 'bad token' } } });
  await run('facebook fail nomsg', api, 'getFacebook', user('facebook', { facebook: '123' }), { 'graph.facebook.com': { status: 400, body: {} } });
  await run('scraping ok', api, 'getScraping', {}, { 'ycombinator': { body: '<html><body><span class="title"><a href="http://a.com">A</a></span><span class="title"><a href="http://b.com">B</a></span><a href="https://c.com">C</a><a href="/rel">R</a></body></html>', headers: { 'content-type': 'text/html' } } });
  await run('scraping fail', api, 'getScraping', {}, { 'ycombinator': { status: 500, body: 'x' } });
  await run('github anon', api, 'getGithub', {}, { 'api.github.com/repos/sahat': { body: { name: 'hackathon-starter', stargazers_count: 5 } } });
  await run('github user no token', api, 'getGithub', { user: { tokens: [] } }, { 'api.github.com/repos/sahat': { body: { name: 'hs' } } });
  await run('github user no tokens prop', api, 'getGithub', { user: {} }, { 'api.github.com/repos/sahat': { body: { name: 'hs' } } });
  await run('github authed', api, 'getGithub', user('github'), { 'api.github.com/repos/sahat': { body: { name: 'hs' } }, 'api.github.com/user/repos': { body: [{ r: 1 }] }, '/events': { body: [{ e: 1 }] }, 'api.github.com/user': { body: { login: 'ann' } } });
  await run('github repo fail', api, 'getGithub', {}, { 'api.github.com/repos/sahat': { status: 500, body: { message: 'x' } } });
  await run('quickbooks ok', api, 'getQuickbooks', user('quickbooks', { quickbooks: 'R1' }), { 'quickbooks': { body: { QueryResponse: { Customer: [{ c: 1 }] } } } });
  await run('quickbooks fail', api, 'getQuickbooks', user('quickbooks', { quickbooks: 'R1' }), { 'quickbooks': { status: 401, statusText: 'Unauthorized', body: {} } });
  await run('nyt ok', api, 'getNewYorkTimes', {}, { 'nytimes': { body: { results: { books: [{ t: 1 }] } } } });
  await run('nyt not ok', api, 'getNewYorkTimes', {}, { 'nytimes': { status: 429, statusText: 'Too Many', body: 'slow down slow down', headers: { 'content-type': 'text/plain', 'x-a': 'b' } } });
  await run('nyt not json', api, 'getNewYorkTimes', {}, { 'nytimes': { body: '<html>', headers: { 'content-type': 'text/html' } } });
  await run('nyt missing', api, 'getNewYorkTimes', {}, { 'nytimes': { body: { results: {} } } });
  await run('nyt network', api, 'getNewYorkTimes', {}, { 'nytimes': new Error('ECONNRESET') });
  const steam = { 'GetRecentlyPlayedGames': { body: { response: { total_count: 1, games: [{ appid: 7 }] } } }, 'GetPlayerAchievements': { body: { playerstats: { achievements: [1] } } }, 'GetPlayerSummaries': { body: { response: { players: [{ p: 1 }] } } }, 'GetOwnedGames': { body: { response: { games: [] } } } };
  await run('steam ok', api, 'getSteam', { user: { steam: '42', tokens: [] } }, steam);
  await run('steam no games', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetRecentlyPlayedGames': { body: { response: {} } } });
  await run('steam zero count', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetRecentlyPlayedGames': { body: { response: { total_count: 0 } } } });
  await run('steam private', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetPlayerAchievements': { status: 403, body: {} } });
  await run('steam ach fail', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetPlayerAchievements': { status: 500, body: {} } });
  await run('steam no ach', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetPlayerAchievements': { body: { playerstats: {} } } });
  await run('steam recent fail', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetRecentlyPlayedGames': { status: 500, body: {} } });
  await run('steam summaries fail', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetPlayerSummaries': { status: 500, body: {} } });
  await run('steam owned fail', api, 'getSteam', { user: { steam: '42', tokens: [] } }, { ...steam, 'GetOwnedGames': { status: 500, body: {} } });
  await run('getStripe', api, 'getStripe');
  await run('getTwilio', api, 'getTwilio');
  await run('postTwilio empty', api, 'postTwilio', { body: {} });
  await run('postTwilio blank msg', api, 'postTwilio', { body: { number: '+1', message: '' } });
  const twitch = { 'helix/users?id': { body: { data: [{ id: 1 }] } }, 'followers': { body: { total: 3 } }, 'streams': { body: { data: [{ user_login: 'top' }] } }, 'users?login': { body: { data: [{ login: 'top' }] } } };
  await run('twitch ok', api, 'getTwitch', user('twitch', { twitch: 'T1' }), twitch);
  await run('twitch empty data', api, 'getTwitch', user('twitch', { twitch: 'T1' }), { ...twitch, 'helix/users?id': { body: { data: [] } }, 'users?login': { body: { data: [] } } });
  await run('twitch user fail', api, 'getTwitch', user('twitch', { twitch: 'T1' }), { ...twitch, 'helix/users?id': { status: 500, body: {} } });
  await run('twitch followers fail', api, 'getTwitch', user('twitch', { twitch: 'T1' }), { ...twitch, 'followers': { status: 500, body: {} } });
  await run('twitch streams fail', api, 'getTwitch', user('twitch', { twitch: 'T1' }), { ...twitch, 'streams': { status: 500, body: {} } });
  await run('twitch login fail', api, 'getTwitch', user('twitch', { twitch: 'T1' }), { ...twitch, 'users?login': { status: 500, body: {} } });
  await run('chart fallback', api, 'getChart', {}, { 'alphavantage': { body: { Note: 'limit' } } });
  const series = {}; for (let i = 0; i < 120; i++) series['2024-01-' + String(i).padStart(3, '0')] = { '4. close': String(100 + i) };
  await run('chart live', api, 'getChart', {}, { 'alphavantage': { body: { 'Time Series (Daily)': series } } });
  await run('chart fail', api, 'getChart', {}, { 'alphavantage': { status: 503, body: {} } });
  const paypal = { 'oauth2/token': { body: { access_token: 'PAT' } }, '/capture': { body: { ok: 1 } }, 'checkout/orders': { body: { id: 'O1', links: [{ rel: 'self', href: 's' }, { rel: 'approve', href: 'https://approve' }] } } };
  await run('paypal ok', api, 'getPayPal', {}, paypal);
  await run('paypal token fail', api, 'getPayPal', {}, { ...paypal, 'oauth2/token': { status: 401, body: {} } });
  await run('paypal order fail', api, 'getPayPal', {}, { ...paypal, 'checkout/orders': { status: 500, body: {} } });
  await run('paypal success ok', api, 'getPayPalSuccess', { session: { orderId: 'O1' } }, paypal);
  await run('paypal success fail', api, 'getPayPalSuccess', { session: { orderId: 'O1' } }, { ...paypal, '/capture': { status: 500, body: {} } });
  await run('paypal success token fail', api, 'getPayPalSuccess', { session: { orderId: 'O1' } }, { ...paypal, 'oauth2/token': { status: 500, body: {} } });
  await run('paypal cancel', api, 'getPayPalCancel', { session: { orderId: 'O1' } });
  await run('getFileUpload', api, 'getFileUpload');
  await run('postFileUpload ok', api, 'postFileUpload', { file: { a: 1 } });
  await run('postFileUpload too large', api, 'postFileUpload', { multerError: { code: 'LIMIT_FILE_SIZE', message: 'big' } });
  await run('postFileUpload other err', api, 'postFileUpload', { multerError: { code: 'X', message: 'other' } });
  await run('postFileUpload nothing', api, 'postFileUpload', {});
  await run('getHereMaps', api, 'getHereMaps');
  await run('getGoogleMaps', api, 'getGoogleMaps');
  const sec = (h, infos) => ({ TOCHeading: h, Information: infos });
  const pub = {
    'cid/2244/JSON': { body: { PC_Compounds: [{ id: 1 }] } },
    '/property/': { body: { PropertyTable: { Properties: [{ MolecularWeight: 180 }] } } },
    '/synonyms/': { body: { InformationList: { Information: [{ Synonym: Array.from({ length: 15 }, (_, i) => 's' + i) }] } } },
    'Safety%20and%20Hazards': { body: { Record: { Section: [{ TOCHeading: 'Other' }, { TOCHeading: 'Safety and Hazards', Section: [sec('Hazards', [{ Value: { StringWithMarkup: [{ String: 'H1' }] } }, { Value: { String: 'H2' } }, { Value: {} }, {}]), { TOCHeading: 'NoInfo' }, sec('', [])] }] } } },
    'Use%20and%20Manufacturing': { body: { Record: { Section: [{ TOCHeading: 'Use and Manufacturing', Section: [{ TOCHeading: 'Uses' }, { TOCHeading: 'Methods of Manufacturing', Information: [{ Value: { StringWithMarkup: [{ String: 'made so' }] } }] }] }] } } },
  };
  await run('pubchem ok', api, 'getPubChem', {}, pub);
  await run('pubchem empty', api, 'getPubChem', {}, {});
  await run('pubchem partial', api, 'getPubChem', {}, { ...pub, 'cid/2244/JSON': new Error('net'), 'Use%20and%20Manufacturing': { body: { Record: { Section: [{ TOCHeading: 'Use and Manufacturing', Section: [{ TOCHeading: 'Methods of Manufacturing', Information: [{ Value: { String: 'plain' } }] }] }] } } }, 'Safety%20and%20Hazards': { body: { Record: { Section: [{ TOCHeading: 'x' }] } } } });
  await run('pubchem manufacturing none', api, 'getPubChem', {}, { ...pub, 'Use%20and%20Manufacturing': { body: { Record: { Section: [{ TOCHeading: 'Use and Manufacturing', Section: [{ TOCHeading: 'Uses' }] }] } } } });
  const wiki = (url) => {
    if (url.includes('list=search')) return { body: { query: { search: [{ title: 'T', snippet: 'a <b>bold</b> and <span class="x">y</span>' }] } } };
    if (url.includes('action=parse')) return { body: { parse: { sections: [{ line: 'History' }, { line: 'Use' }] } } };
    if (url.includes('prop=extracts')) return { body: { query: { pages: { 1: { extract: 'x'.repeat(1200) } } } } };
    return { body: { query: { pages: { 1: { thumbnail: { source: 'http://img' } } } } } };
  };
  await run('wikipedia no query', api, 'getWikipedia', { query: {} }, { 'wikipedia.org': wiki });
  await run('wikipedia query', api, 'getWikipedia', { query: { q: '  Node (js), v-1 ' } }, { 'wikipedia.org': wiki });
  await run('wikipedia bad chars', api, 'getWikipedia', { query: { q: 'a<b>' } }, { 'wikipedia.org': wiki });
  await run('wikipedia too long', api, 'getWikipedia', { query: { q: 'a'.repeat(250) } }, { 'wikipedia.org': wiki });
  await run('wikipedia fail', api, 'getWikipedia', { query: { q: 'node' } }, { 'wikipedia.org': { status: 500, statusText: 'ISE', body: {} } });
  await run('wikipedia short+original', api, 'getWikipedia', { query: {} }, { 'wikipedia.org': (url) => (url.includes('prop=extracts') ? { body: { query: { pages: { 1: { extract: 'short' } } } } } : url.includes('pageimages') ? { body: { query: { pages: { 1: { original: { source: 'http://orig' } } } } } } : url.includes('action=parse') ? { body: {} } : { body: {} }) });
  await run('wikipedia image fail', api, 'getWikipedia', { query: {} }, { 'wikipedia.org': (url) => (url.includes('pageimages') ? { status: 500, statusText: 'X', body: {} } : wiki(url)) });
  await run('giphy ok', api, 'getGiphy', { query: {} }, { 'giphy': { body: { meta: { status: 200 }, data: [{ id: 1, title: 't', images: { fixed_width: { url: 'u' } } }] } } });
  await run('giphy search', api, 'getGiphy', { query: { search: 'cat & dog' } }, { 'giphy': { body: { data: [] } } });
  await run('giphy not ok', api, 'getGiphy', { query: {} }, { 'giphy': { status: 403, statusText: 'Forbidden', body: 'nope' } });
  await run('giphy meta', api, 'getGiphy', { query: {} }, { 'giphy': { body: { meta: { status: 429, msg: 'limit' } } } });
};
