const path = require('node:path');
const fs = require('node:fs');
const crypto = require('node:crypto');
module.exports = async ({ appDir, out, logs }) => {
  const { MongoMemoryServer } = require(path.join(appDir, 'node_modules/mongodb-memory-server'));
  const request = require(path.join(appDir, 'node_modules/supertest'));
  const mongoose = require(path.join(appDir, 'node_modules/mongoose'));
  const mongo = await MongoMemoryServer.create();
  process.env.MONGODB_URI = mongo.getUri();
  process.env.PORT = '0'; process.env.RATE_LIMIT_STRICT = '1000'; process.env.RATE_LIMIT_LOGIN = '1000'; process.env.RATE_LIMIT_GLOBAL = '100000';
  delete global.fetch; // real fetch (requests to external hosts fail fast and identically)
  global.fetch = async () => { throw new Error('network disabled'); };
  const app = require(path.join(appDir, 'app'));
  await new Promise((r) => (mongoose.connection.readyState === 1 ? r() : mongoose.connection.once('open', r)));
  const norm = (s) => String(s || '').replace(/(name="_csrf"[^>]*value=")[^"]*"/g, '$1X"').replace(/(value=")[A-Za-z0-9+/=_-]{24,}(")/g, '$1X$2').replace(/csrf-token" content="[^"]*"/g, 'csrf-token" content="X"').replace(/[a-f0-9]{24}/g, 'OID').replace(/(formData\.append\('_csrf', ')[^']*'/g, "$1X'").replace(/("challenge":")[^"]*"/g, '$1X"');
  const rec = async (name, p) => {
    logs.length = 0;
    let res; try { res = await p; } catch (e) { out.push(JSON.stringify({ name, error: e.message })); return null; }
    const body = norm(res.text);
    out.push(JSON.stringify({ name, status: res.status, location: res.headers.location, type: res.headers['content-type'], xfo: res.headers['x-frame-options'], xss: res.headers['x-xss-protection'], cache: res.headers['cache-control'], powered: res.headers['x-powered-by'], len: body.length, sha: crypto.createHash('sha1').update(body).digest('hex'), nlogs: logs.filter((l) => l[0] !== 'fetch').length }));
    return res;
  };
  const csrfOf = (res) => { const m = /name="_csrf"[^>]*value="([^"]*)"/.exec(res.text) || /value="([^"]*)"[^>]*name="_csrf"/.exec(res.text); return m ? m[1] : null; };
  const anon = request.agent(app);
  for (const u of ['/', '/login', '/signup', '/forgot', '/contact', '/api', '/ai', '/api/upload', '/ai/llm-camera', '/api/stripe', '/api/twilio', '/api/here-maps', '/api/google-maps', '/ai/llm-classifier', '/api/chart', '/api/scraping', '/api/pubchem', '/api/wikipedia', '/api/wikipedia?q=node', '/api/giphy', '/api/nyt', '/api/foursquare', '/api/github', '/api/paypal', '/api/paypal/cancel', '/account', '/login', '/account/verify', '/api/steam', '/api/tumblr', '/api/google/drive', '/auth/failure', '/login', '/api', '/auth/failure', '/login/webauthn-start', '/account/webauthn/register', '/nonexistent', '/nonexistent.png', '/js/lib/jquery.min.js', '/css/lib/cookieconsent.min.css', '/css/main.css', '/webfonts/fa-solid-900.woff2', '/reset/abc', '/reset/zz!', '/login/verify/zzz', '/login/verify/abcdef', '/account/unlink/github', '/login/2fa', '/login/2fa/totp', '/logout', '/auth/failure', '/ai/ai-agent']) {
    await rec('GET ' + u, anon.get(u));
  }
  await rec('HEAD lib', anon.head('/js/lib/bootstrap.min.js'));
  await rec('POST /login no csrf', anon.post('/login').type('form').send({ email: 'a@b.c', password: 'x' }));
  let page = await anon.get('/login'); let csrf = csrfOf(page);
  out.push(JSON.stringify({ name: 'csrf found', ok: !!csrf }));
  const post = (agent, url, data) => agent.post(url).type('form').send({ _csrf: csrf, ...data });
  await rec('POST /login bad email', post(anon, '/login', { email: 'nope', password: 'x' }));
  await rec('GET /login after bad', anon.get('/login'));
  await rec('POST /login blank password', post(anon, '/login', { email: 'tl.user.one@gmail.com', password: '' }));
  await rec('POST /login unknown', post(anon, '/login', { email: 'tl.user.one@gmail.com', password: 'whatever12' }));
  await rec('GET /login after unknown', anon.get('/login'));
  await rec('POST /login by link unknown', post(anon, '/login', { email: 'tl.user.one@gmail.com', loginByEmailLink: 'on' }));
  await rec('POST /signup invalid', post(anon, '/signup', { email: 'x', password: 'short', confirmPassword: 'other' }));
  await rec('GET /signup after invalid', anon.get('/signup'));
  await rec('POST /forgot invalid', post(anon, '/forgot', { email: 'x' }));
  await rec('POST /forgot unknown', post(anon, '/forgot', { email: 'tl.user.one@gmail.com' }));
  await rec('GET /forgot after', anon.get('/forgot'));
  await rec('POST /reset invalid', post(anon, '/reset/zz', { password: 'a', confirm: 'b' }));
  await rec('POST /contact invalid', post(anon, '/contact', { name: '', email: 'x', message: '', 'g-recaptcha-response': '' }));
  await rec('GET /contact after', anon.get('/contact'));
  await rec('POST /api/twilio empty', post(anon, '/api/twilio', {}));
  await rec('GET /api/twilio after', anon.get('/api/twilio'));
  await rec('POST /ai/llm-classifier empty', post(anon, '/ai/llm-classifier', { inputText: '' }));
  await rec('POST /ai/llm-classifier text', post(anon, '/ai/llm-classifier', { inputText: 'refund please' }));
  await rec('POST /ai/ai-agent/chat empty', post(anon, '/ai/ai-agent/chat', {}));
  await rec('POST /login/2fa bad', post(anon, '/login/2fa', { code: 'abc' }));
  await rec('POST /login/2fa no session', post(anon, '/login/2fa', { code: '123456' }));
  await rec('POST /login/2fa/totp no session', post(anon, '/login/2fa/totp', { code: '123456' }));
  await rec('POST /login/2fa/resend', post(anon, '/login/2fa/resend', {}));
  await rec('POST /login/webauthn-start', post(anon, '/login/webauthn-start', { email: 'A@B.c', useEmailWithBiometrics: 'on' }));
  await rec('POST /login/webauthn-verify', post(anon, '/login/webauthn-verify', {}));
  await rec('POST /account/profile anon', post(anon, '/account/profile', {}));
  await rec('POST /api/upload no file', anon.post('/api/upload').field('_csrf', csrf));
  await rec('POST /api/upload file', anon.post('/api/upload').field('_csrf', csrf).attach('myFile', Buffer.from('hello'), 'a.txt'));
  await rec('GET /api/upload after', anon.get('/api/upload'));
  await rec('POST /api/upload big', anon.post('/api/upload').field('_csrf', csrf).attach('myFile', Buffer.alloc(1024 * 1024 + 10), 'big.bin'));
  await rec('GET /api/upload after big', anon.get('/api/upload'));
  await rec('POST /api/upload bad csrf', anon.post('/api/upload').field('_csrf', 'bad').attach('myFile', Buffer.from('hello'), 'a.txt'));
  await rec('POST /ai/llm-camera no image', anon.post('/ai/llm-camera').field('_csrf', csrf));
  // signup / account flow against the in-memory database
  const user = request.agent(app);
  page = await user.get('/signup'); csrf = csrfOf(page);
  await rec('POST /signup ok', post(user, '/signup', { email: 'TL.User.One@gmail.com', password: 'correct horse', confirmPassword: 'correct horse' }));
  await rec('GET / logged in', user.get('/'));
  await rec('GET /account', user.get('/account'));
  await rec('GET /login logged in', user.get('/login'));
  await rec('GET /signup logged in', user.get('/signup'));
  await rec('GET /api logged in', user.get('/api'));
  await rec('GET /api/steam logged in', user.get('/api/steam'));
  await rec('GET /auth/failure logged in', user.get('/auth/failure'));
  await rec('GET /api again', user.get('/api'));
  page = await user.get('/account'); csrf = csrfOf(page);
  await rec('POST /account/profile bad', post(user, '/account/profile', { email: 'x' }));
  await rec('POST /account/profile ok', post(user, '/account/profile', { email: 'tl.user.one@gmail.com', name: 'TL User', gender: 'other', location: 'Here', website: 'https://example.org' }));
  await rec('GET /account after profile', user.get('/account'));
  await rec('POST /account/profile picture bad', post(user, '/account/profile', { email: 'tl.user.one@gmail.com', pictureSource: 'github' }));
  await rec('POST /account/profile picture gravatar', post(user, '/account/profile', { email: 'tl.user.one@gmail.com', name: 'TL User', pictureSource: ' gravatar ' }));
  await rec('POST /account/password mismatch', post(user, '/account/password', { password: 'newpassword1', confirmPassword: 'x' }));
  await rec('POST /account/password ok', post(user, '/account/password', { password: 'newpassword1', confirmPassword: 'newpassword1' }));
  await rec('POST /account/2fa/email/enable', post(user, '/account/2fa/email/enable', {}));
  await rec('GET /account/2fa/totp/setup', user.get('/account/2fa/totp/setup'));
  await rec('POST /account/2fa/totp/setup bad', post(user, '/account/2fa/totp/setup', { code: '1' }));
  await rec('POST /account/2fa/totp/setup nosession', post(user, '/account/2fa/totp/setup', { code: '123456' }));
  await rec('POST /account/2fa/totp/remove', post(user, '/account/2fa/totp/remove', {}));
  await rec('POST /account/2fa/email/remove', post(user, '/account/2fa/email/remove', {}));
  await rec('GET /account/verify/zz', user.get('/account/verify/zz'));
  await rec('GET /account/verify/abcdef', user.get('/account/verify/abcdef'));
  await rec('GET /account/unlink/github', user.get('/account/unlink/github'));
  await rec('GET /account after unlink', user.get('/account'));
  await rec('POST /account/webauthn/register', post(user, '/account/webauthn/register', {}));
  await rec('POST /account/webauthn/verify', post(user, '/account/webauthn/verify', {}));
  await rec('POST /account/webauthn/remove', post(user, '/account/webauthn/remove', {}));
  await rec('GET /ai/ai-agent user', user.get('/ai/ai-agent'));
  await rec('POST /ai/ai-agent/reset', post(user, '/ai/ai-agent/reset', {}));
  await rec('GET /ai/rag', user.get('/ai/rag'));
  await rec('POST /ai/rag/ask empty', post(user, '/ai/rag/ask', { question: '' }));
  await rec('POST /ai/rag/ingest', post(user, '/ai/rag/ingest', {}));
  await rec('POST /account/logout-everywhere', post(user, '/account/logout-everywhere', {}));
  await rec('GET /account after logout everywhere', user.get('/account'));
  // log in again with the new password, then delete the account
  const again = request.agent(app);
  page = await again.get('/login'); csrf = csrfOf(page);
  await rec('POST /login wrong password', post(again, '/login', { email: 'tl.user.one@gmail.com', password: 'wrong wrong' }));
  await rec('GET /login after wrong', again.get('/login'));
  await rec('POST /login ok', post(again, '/login', { email: 'TL.user.ONE@gmail.com', password: 'newpassword1' }));
  await rec('GET /account relogin', again.get('/account'));
  await rec('POST /signup existing email', post(request.agent(app), '/signup', { email: 'tl.user.one@gmail.com', password: 'correct horse', confirmPassword: 'correct horse' }));
  page = await again.get('/account'); csrf = csrfOf(page);
  await rec('GET /logout', again.get('/logout'));
  await rec('GET /account after logout', again.get('/account'));
  page = await again.get('/login'); csrf = csrfOf(page);
  await rec('POST /login ok 2', post(again, '/login', { email: 'tl.user.one@gmail.com', password: 'newpassword1' }));
  page = await again.get('/account'); csrf = csrfOf(page);
  await rec('POST /account/delete', post(again, '/account/delete', {}));
  await rec('GET /account after delete', again.get('/account'));
  const users = await mongoose.connection.db.collection('users').countDocuments();
  out.push(JSON.stringify({ name: 'users left', users }));
  for (const d of ['rag_input/ingested', 'rag_input', 'uploads']) { const p = path.join(appDir, d); if (fs.existsSync(p)) { for (const f of fs.readdirSync(p)) { const fp = path.join(p, f); if (fs.statSync(fp).isFile()) fs.unlinkSync(fp); } fs.rmdirSync(p); } }
  await mongoose.disconnect();
  await mongo.stop();
};
