// TL AST -> JavaScript (ES2022 module). Semantics follow the TL/JS host binding:
//   records -> classes, enums -> tagged classes, T? -> undefined, errors -> thrown TL errors
//   (checked statically in later versions), unpropagated calls to erroring functions -> Ok/Err values.

import fs from 'node:fs';
import path from 'node:path';
import { TLError } from './errors.js';
import { JS_GLOBALS } from './prelude.js';

const JS_BINARY = { '+': '+', '-': '-', '/': '/', '%': '%', '**': '**', '>': '>', '>=': '>=', '+%': '+', '-%': '-', '*%': '*' };

export function emitModule(ast, opts) {
  const e = new Emitter(opts);
  return e.program(ast);
}

class Emitter {
  constructor(opts) {
    this.opts = opts;            // { runtime, file, dir, defs, fields, exports }
    this.out = [];
    this.ind = 0;
    this.tmp = 0;
    this.loops = [];
    this.propagating = false;
    this.inFn = 0;
  }

  line(s) { this.out.push('  '.repeat(this.ind) + s); }
  t(prefix = 't') { return `$${prefix}${this.tmp++}`; }
  capture(fn) {
    const saved = this.out;
    this.out = [];
    const code = fn();
    const pre = this.out;
    this.out = saved;
    return { code, pre };
  }
  flush(pre) { for (const l of pre) this.out.push(l); }
  err(msg, node, code = 'E700') { return new TLError(code, msg, this.opts.file, node?.pos ?? -1); }

  // ───────────────────────── module ─────────────────────────
  program(ast) {
    this.line(`// Generated by tlc from ${this.opts.file}.tl — do not edit.`);
    this.line(`import * as $ from ${JSON.stringify(this.opts.runtime)};`);
    const body = ast.body;
    for (const s of body) if (s.k === 'Import') this.importDecl(s);
    this.defDecls(ast);
    const order = (k) => ({ TypeDecl: 0, ErrorDecl: 0, Trait: 1, Impl: 2, Ext: 2 })[k] ?? 3;
    const hoisted = body.filter((s) => order(s.k) < 3).sort((a, b) => order(a.k) - order(b.k));
    for (const s of hoisted) this.stmt(s, true);
    const rest = body.filter((s) => s.k !== 'Import' && order(s.k) === 3);
    this.stmts(rest, null, true);
    return this.out.join('\n') + '\n';
  }

  importDecl(s) {
    if (s.kind === 'js') { this.line(`import * as ${s.js}$ns from ${JSON.stringify(s.from)};`); this.line(`const ${s.js} = ${s.js}$ns.default ?? ${s.js}$ns;`); return; }
    if (s.external) {
      if (s.external === 'node') this.line(`import * as ${s.js} from ${JSON.stringify(s.from)};`);
      else { this.line(`import * as ${s.js}$ns from ${JSON.stringify(s.from)};`); this.line(`const ${s.js} = ${s.js}$ns.default ?? ${s.js}$ns;`); }
      return;
    }
    if (s.std) return;
    const from = JSON.stringify(`./${s.module}.js`);
    if (s.named) this.line(`import { ${s.named.map((n) => (n.name === n.local ? n.name : `${n.name} as ${n.local}`)).join(', ')} } from ${from};`);
    else this.line(`import * as ${s.js} from ${from};`);
  }

  /** Types, errors and constants declared only in tl.def get their runtime definitions here. */
  defDecls(ast) {
    const declared = new Set(ast.body.filter((s) => s.k === 'TypeDecl' || s.k === 'ErrorDecl').map((s) => s.name));
    for (const [sym, d] of this.opts.defs) {
      if (declared.has(sym)) continue;
      if (d.kind === 'type' && d.fields) {
        const fields = d.fields.map((f) => `{ js: ${JSON.stringify(f.long)}${f.default !== null ? `, def: () => ${defaultJs(f.default)}` : ''} }`);
        this.line(`export const ${d.name} = $.record(${JSON.stringify(d.name)}, [${fields.join(', ')}]);`);
      } else if (d.kind === 'type' && d.tuple) {
        this.line(`export const ${d.name} = $.tupleType(${JSON.stringify(d.name)}, ${d.tuple.length});`);
      } else if (d.kind === 'error') {
        this.line(`export const ${d.name} = $.errorType(${JSON.stringify(d.name)}, ${JSON.stringify((d.fields || []).map((f) => f.long))}, ${JSON.stringify(d.doc || '')});`);
      } else if (d.kind === 'const' && d.value !== null) {
        this.line(`export const ${d.name} = ${defaultJs(d.value)};`);
      }
    }
  }

  // ───────────────────────── statements ─────────────────────────
  /**
   * Emits a statement list. `sink` receives the JS of the final expression when the list
   * produces a value (function results, block expressions); null means the value is unused.
   */
  stmts(list, sink, top = false) {
    for (let i = 0; i < list.length; i++) {
      const s = list[i];
      const last = i === list.length - 1;
      if (s.k === 'Defer') {
        const rest = list.slice(i + 1);
        this.line('try {');
        this.ind++;
        this.stmts(rest, sink, top);
        this.ind--;
        if (s.err) {
          const e = this.t('e');
          this.line(`} catch (${e}) {`);
          this.ind++; this.exprStmt(s.expr); this.line(`throw ${e};`); this.ind--;
          this.line('}');
        } else {
          this.line('} finally {');
          this.ind++; this.exprStmt(s.expr); this.ind--;
          this.line('}');
        }
        return;
      }
      if (last && sink) this.valueStmt(s, sink);
      else this.stmt(s, top);
    }
  }

  /** Last statement of a value-producing body. */
  valueStmt(s, sink) {
    switch (s.k) {
      case 'ExprStmt': {
        if (isBlockExpr(s.expr)) return this.blockStmt(s.expr, sink);
        const { code, pre } = this.capture(() => this.expr(s.expr));
        this.flush(pre);
        sink(code);
        return;
      }
      case 'If': case 'Match': case 'Try': case 'Block': case 'With': return this.blockStmt(s, sink);
      default: return this.stmt(s);
    }
  }

  exprStmt(e) {
    if (isBlockExpr(e)) return this.blockStmt(e, null);
    const { code, pre } = this.capture(() => this.expr(e));
    this.flush(pre);
    this.line(`${code};`);
  }

  stmt(s, top = false) {
    switch (s.k) {
      case 'Import': return;
      case 'ExprStmt': return this.exprStmt(s.expr);
      case 'Let': return this.letStmt(s, top);
      case 'Assign': return this.assign(s);
      case 'Fn': return this.fnDecl(s, top);
      case 'TypeDecl': return this.typeDecl(s, top);
      case 'ErrorDecl': return this.line(`${top ? 'export ' : ''}const ${s.js} = $.errorType(${JSON.stringify(s.canonical)}, ${JSON.stringify(s.fields)}, ${JSON.stringify(s.doc || '')});`);
      case 'Trait': return this.traitDecl(s, top);
      case 'Impl': return this.implDecl(s);
      case 'Ext': return this.extDecl(s);
      case 'Mod': return this.modDecl(s, top);
      case 'If': case 'Match': case 'Try': case 'Block': case 'With': return this.blockStmt(s, null);
      case 'While': case 'For': case 'Loop': case 'Repeat': case 'DoWhile': return this.loopStmt(s, null);
      case 'Guard': {
        const c = this.cond(s.cond);
        this.line(`if (!(${c})) {`);
        this.ind++; this.stmts(s.body, null); this.ind--;
        this.line('}');
        return;
      }
      case 'Return': {
        if (!this.inFn) throw this.err("'^' returns from a function; at the top level of a module there is nothing to return from", s, 'E170');
        if (!s.value) return this.line('return;');
        if (isBlockExpr(s.value)) { const v = this.t('r'); this.line(`let ${v};`); this.blockStmt(s.value, (c) => this.line(`${v} = ${c};`)); return this.line(`return ${v};`); }
        const { code, pre } = this.capture(() => this.expr(s.value));
        this.flush(pre);
        return this.line(`return ${code};`);
      }
      case 'Break': {
        const loop = this.findLoop(s.label, s);
        if (s.value) {
          if (!loop.res) throw this.err('break with a value is only allowed in a loop used as a value', s, 'E171');
          const { code, pre } = this.capture(() => this.expr(s.value));
          this.flush(pre);
          this.line(`${loop.res} = ${code};`);
        }
        if (loop.broke) this.line(`${loop.broke} = true;`);
        return this.line(`break ${loop.label};`);
      }
      case 'Continue': {
        const loop = this.findLoop(s.label, s);
        return this.line(`continue ${loop.label};`);
      }
      case 'Raise': {
        const { code, pre } = this.capture(() => this.expr(s.value));
        this.flush(pre);
        return this.line(`throw $.raise(${code});`);
      }
      case 'Yield': {
        const { code, pre } = this.capture(() => (s.value ? this.expr(s.value) : ''));
        this.flush(pre);
        return this.line(s.from ? `yield* $.iter(${code});` : `yield ${code};`);
      }
      case 'Test': {
        this.line(`$.test(${JSON.stringify(s.name)}, async () => {`);
        this.ind++; this.inFn++;
        this.withOptQ(s.usesOptQ, () => this.stmts(s.body, null));
        this.inFn--; this.ind--;
        return this.line('});');
      }
      case 'Scope': {
        this.line(`await $.scope(async (${s.name}) => {`);
        this.ind++; this.inFn++; this.stmts(s.body, null); this.inFn--; this.ind--;
        return this.line('});');
      }
      case 'Contract': {
        if (s.kind === 'requires') { const c = this.cond(s.cond); return this.line(`$.assert(${c}, "requires failed");`); }
        return;
      }
      case 'Defer': return this.stmts([s], null);
      default: throw this.err(`cannot compile statement '${s.k}'`, s);
    }
  }

  findLoop(label, node) {
    for (let i = this.loops.length - 1; i >= 0; i--) {
      if (!label || this.loops[i].user === label) return this.loops[i];
    }
    throw this.err(label ? `no enclosing loop labeled '${label}` : "'break'/'continue' outside a loop", node, 'E172');
  }

  letStmt(s, top) {
    const kw = top && s.decl === 'const' ? 'export const' : 'let';
    if (isBlockExpr(s.value) && s.pat.k === 'PBind') {
      this.line(`${kw === 'export const' ? 'export let' : 'let'} ${s.pat.js};`);
      this.blockStmt(s.value, (c) => this.line(`${s.pat.js} = ${c};`));
      return;
    }
    const { code, pre } = this.capture(() => (isBlockExpr(s.value) ? this.blockValue(s.value) : this.expr(s.value)));
    this.flush(pre);
    const target = this.destructure(s.pat);
    if (target) return this.line(`${kw} ${target} = ${code};`);
    // refutable-looking pattern: fall back to a checked match
    const v = this.t('v');
    this.line(`const ${v} = ${code};`);
    const vars = new Set();
    const c = this.pat(s.pat, v, vars);
    if (vars.size) this.line(`let ${[...vars].join(', ')};`);
    this.line(`if (!(${c})) throw $.panicErr("pattern did not match");`);
  }

  /** JS destructuring target for an irrefutable pattern, or null. */
  destructure(p) {
    switch (p.k) {
      case 'PBind': return p.js;
      case 'PWild': return this.t('_');
      case 'PTuple': { const items = p.items.map((x) => this.destructure(x)); return items.includes(null) ? null : `[${items.join(', ')}]`; }
      case 'PSlice': {
        const out = [];
        for (let i = 0; i < p.items.length; i++) {
          const x = p.items[i];
          if (x.k === 'PRest') { if (i !== p.items.length - 1) return null; out.push(x.js ? `...${x.js}` : ''); continue; }
          const d = this.destructure(x);
          if (d === null) return null;
          out.push(d);
        }
        return `[${out.join(', ')}]`;
      }
      case 'PRecord': {
        const fields = p.fields.map((f) => { const d = this.destructure(f.pat); return d === null ? null : `${JSON.stringify(this.fieldJs(p.sym, f.name))}: ${d}`; });
        return fields.includes(null) ? null : `{ ${fields.join(', ')} }`;
      }
      default: return null;
    }
  }

  fieldJs(sym, name) {
    const f = sym?.fields?.find?.((x) => x.name === name);
    if (f) return f.js;
    return this.opts.fields.get(name) || name;
  }

  assign(s) {
    const { code: value, pre } = this.capture(() => this.expr(s.value));
    this.flush(pre);
    const t = s.target;
    const op = s.op;
    if (t.k === 'Index') {
      const obj = this.expr(t.obj);
      const idx = this.expr(t.index);
      if (op === '=') return this.line(`$.setIdx(${obj}, ${idx}, ${value});`);
      const o = this.t('o'), k = this.t('k');
      this.line(`{ const ${o} = ${obj}, ${k} = ${idx}; $.setIdx(${o}, ${k}, ${this.compound(op, `$.idx(${o}, ${k})`, value)}); }`);
      return;
    }
    if (t.k === 'Member' && !/^\d+$/.test(t.name) && !(t.obj.k === 'Ident' && t.obj.name === 'self')) {
      // maps and objects are both assignable with `.name` (runtime decides)
      const obj = this.expr(t.obj);
      const key = JSON.stringify(t.field || this.opts.fields.get(t.name) || t.name);
      if (op === '=') return this.line(`$.setm(${obj}, ${key}, ${value});`);
      const o = this.t('o');
      this.line(`{ const ${o} = ${obj}; $.setm(${o}, ${key}, ${this.compound(op, `$.get(${o}, ${key})`, value)}); }`);
      return;
    }
    const target = t.k === 'Member' ? this.memberTarget(t) : this.expr(t);
    if (op === '=') return this.line(`${target} = ${value};`);
    if (op === '//=') return this.line(`${target} = $.fdiv(${target}, ${value});`);
    return this.line(`${target} ${op} ${value};`);
  }

  compound(op, cur, value) {
    const bin = op.slice(0, -1);
    if (bin === '//') return `$.fdiv(${cur}, ${value})`;
    return `(${cur} ${bin} ${value})`;
  }

  memberTarget(m) {
    const obj = this.expr(m.obj);
    if (/^\d+$/.test(m.name)) return `${obj}[${m.name}]`;
    return `${obj}.${m.field || this.opts.fields.get(m.name) || m.name}`;
  }

  // ───────────────────────── functions ─────────────────────────
  params(ps) {
    const pre = [];
    const list = ps.map((p) => {
      let target = this.destructure(p.pat);
      if (target === null) { target = this.t('a'); pre.push([p.pat, target]); }
      if (p.variadic) return `...${target}`;
      if (p.def) return `${target} = ${this.expr(p.def)}`;
      return target;
    });
    return { list: list.join(', '), pre };
  }

  fnDecl(s, top) {
    const kw = `${s.async ? 'async ' : ''}function${s.gen ? '*' : ''}`;
    const { list } = this.params(s.params);
    if (!s.body) return;
    this.line(`${top ? 'export ' : ''}${kw} ${s.js}(${list}) {`);
    this.paramChecks(s.params);
    this.fnBody(s);
    this.line('}');
  }

  /** `fn f s:str n:int?` checks its annotated parameters at run time (simple kinds only; other types are erased). */
  paramChecks(ps) {
    for (const p of ps) {
      if (!p.ann || p.pat.k !== 'PBind' || p.variadic) continue;
      const m = /^([a-z][a-z0-9]*)(\?)?$/.exec(p.ann);
      if (!m || !CHECKED_KINDS[m[1]]) continue;
      this.ind++;
      this.line(`$.check(${p.pat.js}, ${JSON.stringify(CHECKED_KINDS[m[1]])}, ${JSON.stringify(p.pat.name)}, ${!!m[2]});`);
      this.ind--;
    }
  }

  fnBody(s, selfLine = false) {
    this.ind++;
    this.inFn++;
    const savedLoops = this.loops;
    this.loops = [];
    if (selfLine) this.line('const self = this;');
    const sink = s.gen ? null : (c) => this.line(`return ${c};`);
    this.withOptQ(s.usesOptQ, () => this.stmts(s.body, sink));
    this.loops = savedLoops;
    this.inFn--;
    this.ind--;
  }

  /** Functions that use `?` on optionals return `none` when a value is missing (R-24.2). */
  withOptQ(uses, fn) {
    if (!uses) return fn();
    const e = this.t('e');
    this.line('try {');
    this.ind++; fn(); this.ind--;
    this.line(`} catch (${e}) { if (${e} === $.NONE) return undefined; throw ${e}; }`);
  }

  methodEntries(methods) {
    const inst = [];
    const stat = [];
    const getters = [];
    for (const m of methods) {
      const { list } = this.params(m.params);
      const kw = `${m.async ? 'async ' : ''}function${m.gen ? '*' : ''}`;
      const cap = this.capture(() => { this.ind++; this.line(`${JSON.stringify(m.name)}: ${kw}(${list}) {`); this.fnBody(m, m.self); this.line('},'); this.ind--; });
      (m.getter ? getters : m.self ? inst : stat).push(...cap.pre);
    }
    return { inst, stat, getters };
  }

  typeDecl(s, top) {
    const ex = top ? 'export ' : '';
    if (s.variants.length) {
      const vs = s.variants.map((v) => `{ name: ${JSON.stringify(v.name)}, arity: ${v.arity}${v.named ? `, named: ${JSON.stringify(v.named)}` : ''}${v.value ? `, value: ${this.expr(v.value)}` : ''} }`);
      this.line(`${ex}const ${s.js} = $.enumType(${JSON.stringify(s.canonical)}, [${vs.join(', ')}]);`);
      return;
    }
    if (s.tuple) return this.line(`${ex}const ${s.js} = $.tupleType(${JSON.stringify(s.canonical)}, ${s.tuple.length});`);
    const fields = s.fields.map((f) => {
      const def = f.def ? `, def: () => ${this.expr(f.def)}` : f.defText ? `, def: () => ${defaultJs(f.defText)}` : '';
      return `{ js: ${JSON.stringify(f.js)}${def}${f.embed ? ', embed: true' : ''} }`;
    });
    this.line(`${ex}const ${s.js} = $.record(${JSON.stringify(s.canonical)}, [${fields.join(', ')}]${s.base ? `, ${this.expr(s.base)}` : ''});`);
  }

  traitDecl(s, top) {
    const { inst } = this.methodEntries(s.methods);
    this.line(`${top ? 'export ' : ''}const ${s.js} = $.trait(${JSON.stringify(s.name)}, {`);
    this.flush(inst);
    this.line('});');
  }

  implDecl(s) {
    const { inst, stat, getters } = this.methodEntries(s.methods);
    const target = s.typeSym?.js || s.type;
    const builtin = ['str', 'int', 'float', 'f64', 'f32', 'i32', 'i64', 'u8', 'u32', 'u64', 'bool', 'list', 'map', 'set'].includes(s.type) || /^\[/.test(s.type);
    if (builtin) return this.extDecl(s);
    this.line(`$.impl(${target}, {`);
    this.flush(inst);
    this.line('}, {');
    this.flush(stat);
    const tr = s.trait && s.traitSym?.kind === 'trait' ? s.traitSym.js : 'null';
    if (getters.length) { this.line(`}, ${tr}, {`); this.flush(getters); this.line('});'); }
    else this.line(`}${tr !== 'null' ? `, ${tr}` : ''});`);
  }

  extDecl(s) {
    const { inst } = this.methodEntries(s.methods);
    if (s.typeSym && ['type'].includes(s.typeSym.kind)) {
      this.line(`$.impl(${s.typeSym.js}, {`); this.flush(inst); this.line('}, {});');
      return;
    }
    this.line(`$.ext(${JSON.stringify(s.type.replace(/^\[.*\]$/, 'list'))}, {`);
    this.flush(inst);
    this.line('});');
  }

  modDecl(s, top) {
    this.line(`${top ? 'export ' : ''}const ${s.js} = (() => {`);
    this.ind++;
    this.stmts(s.body, null);
    this.line(`return { ${s.exports.map((x) => (x.name === x.js ? x.js : `${JSON.stringify(x.name)}: ${x.js}`)).join(', ')} };`);
    this.ind--;
    this.line('})();');
  }

  // ───────────────────────── block constructs ─────────────────────────
  /** Emits an If/Match/Try/Block/With (statement or value) — `sink` receives the value. */
  blockStmt(s, sink) {
    switch (s.k) {
      case 'If': {
        s.branches.forEach((b, i) => {
          const c = this.cond(b.cond, i > 0);
          this.line(`${i === 0 ? '' : '} else '}if (${c}) {`);
          this.ind++; this.stmts(b.body, sink); this.ind--;
        });
        if (s.else) { this.line('} else {'); this.ind++; this.stmts(s.else, sink); this.ind--; }
        this.line('}');
        return;
      }
      case 'Match': return this.match(s, sink);
      case 'Try': return this.tryStmt(s, sink);
      case 'Block': this.line('{'); this.ind++; this.stmts(s.body, sink); this.ind--; this.line('}'); return;
      case 'With': {
        const { code, pre } = this.capture(() => this.expr(s.expr));
        this.flush(pre);
        const r = this.t('r');
        this.line('{');
        this.ind++;
        this.line(`const ${r} = ${code};`);
        const target = this.destructure(s.pat) || this.t('w');
        this.line(`const ${target} = $.enter(${r});`);
        this.line('try {');
        this.ind++; this.stmts(s.body, sink); this.ind--;
        this.line(`} finally { $.leave(${r}); }`);
        this.ind--;
        this.line('}');
        return;
      }
      case 'While': case 'For': case 'Loop': case 'Repeat': case 'DoWhile': return this.loopStmt(s, sink);
      default: {
        const { code, pre } = this.capture(() => this.expr(s));
        this.flush(pre);
        if (sink) sink(code); else this.line(`${code};`);
      }
    }
  }

  /** Value of a block expression in expression position: hoisted into a temp. */
  blockValue(e) {
    const v = this.t('v');
    this.line(`let ${v};`);
    this.blockStmt(e, (c) => this.line(`${v} = ${c};`));
    return v;
  }

  match(s, sink) {
    this.line('{');
    this.ind++;
    let subj = null;
    if (s.subject) {
      const { code, pre } = this.capture(() => this.expr(s.subject));
      this.flush(pre);
      subj = this.t('m');
      this.line(`const ${subj} = ${code};`);
    }
    const vars = new Set();
    const conds = s.arms.map((a) => {
      let c;
      if (s.subject) c = this.pat(a.pat, subj, vars);
      else c = a.cond ? this.expr(a.cond) : 'true';
      if (a.guard) c = `${c} && ${this.expr(a.guard)}`;
      return c;
    });
    if (vars.size) this.line(`let ${[...vars].join(', ')};`);
    s.arms.forEach((a, i) => {
      this.line(`${i === 0 ? '' : '} else '}if (${conds[i]}) {`);
      this.ind++; this.stmts(a.body, sink); this.ind--;
    });
    if (s.arms.length) {
      this.line('} else {');
      this.line(`  throw $.panicErr(${JSON.stringify(`no match arm for value`)}, ${subj || 'undefined'});`);
      this.line('}');
    }
    this.ind--;
    this.line('}');
  }

  tryStmt(s, sink) {
    this.line('try {');
    this.ind++; this.stmts(s.body, sink); this.ind--;
    if (s.catches.length) {
      const e = this.t('e');
      this.line(`} catch (${e}) {`);
      this.ind++;
      this.line(`if (${e} === $.NONE || $.isPanic(${e})) throw ${e};`);
      const vars = new Set();
      const conds = s.catches.map((c) => (c.pat ? this.pat(c.pat, e, vars, true) : 'true'));
      if (vars.size) this.line(`let ${[...vars].join(', ')};`);
      s.catches.forEach((c, i) => {
        this.line(`${i === 0 ? '' : '} else '}if (${conds[i]}) {`);
        this.ind++; this.stmts(c.body, sink); this.ind--;
      });
      this.line(`} else throw ${e};`);
      this.ind--;
    }
    if (s.fin) { this.line('} finally {'); this.ind++; this.stmts(s.fin, null); this.ind--; }
    this.line('}');
  }

  loopStmt(s, sink) {
    const user = s.label || null;
    const label = user ? safeLabel(user) : `$L${this.tmp++}`;
    const valueLoop = !!sink && (s.k === 'Loop' || s.else);
    const res = valueLoop ? this.t('lv') : null;
    const broke = s.else ? this.t('b') : null;
    if (res) this.line(`let ${res};`);
    if (broke) this.line(`let ${broke} = false;`);
    this.loops.push({ label, user, res, broke });
    const body = () => { this.ind++; this.stmts(s.body, null); this.ind--; };
    switch (s.k) {
      case 'Loop': this.line(`${label}: while (true) {`); body(); this.line('}'); break;
      case 'While': {
        const { code, pre } = this.capture(() => this.cond(s.cond));
        if (!pre.length) { this.line(`${label}: while (${code}) {`); body(); this.line('}'); }
        else {
          this.line(`${label}: while (true) {`);
          this.ind++; this.flush(pre); this.line(`if (!(${code})) break;`); this.ind--;
          body();
          this.line('}');
        }
        break;
      }
      case 'Repeat': {
        const n = this.expr(s.count);
        const i = s.v || this.t('i');
        this.line(`${label}: for (let ${i} = 0; ${i} < ${n}; ${i}++) {`); body(); this.line('}');
        break;
      }
      case 'DoWhile': {
        const hoisted = s.body.filter((x) => x.k === 'Let' && x.pat.k === 'PBind');
        if (hoisted.length) this.line(`let ${hoisted.map((x) => x.pat.js).join(', ')};`);
        for (const h of hoisted) h.assignOnly = true;
        this.line(`${label}: do {`);
        this.ind++;
        for (const x of s.body) {
          if (x.assignOnly) { const { code, pre } = this.capture(() => this.expr(x.value)); this.flush(pre); this.line(`${x.pat.js} = ${code};`); }
          else this.stmt(x);
        }
        this.ind--;
        this.line(`} while (${this.cond(s.cond)});`);
        break;
      }
      case 'For': this.forLoop(s, label, body); break;
      default:
    }
    this.loops.pop();
    if (s.else) {
      this.line(`if (!${broke}) {`);
      this.ind++; this.stmts(s.else, valueLoop ? (c) => this.line(`${res} = ${c};`) : null); this.ind--;
      this.line('}');
    }
    if (valueLoop) sink(res);
  }

  forLoop(s, label, body) {
    const it = s.iter;
    const simple = s.pat.k === 'PBind';
    // counted ranges compile to plain for-loops
    if (simple && it.k === 'Range' && it.lo && it.hi && !s.await) {
      const lo = this.expr(it.lo), hi = this.expr(it.hi);
      const step = it.step ? this.expr(it.step) : '1';
      const hv = this.t('h');
      this.line(`${label}: for (let ${s.pat.js} = ${lo}, ${hv} = ${hi}; ${s.pat.js} ${it.incl ? '<=' : '<'} ${hv}; ${s.pat.js} += ${step}) {`);
      body();
      this.line('}');
      return;
    }
    if (s.mode === 'mut' && simple) {
      const arr = this.expr(it);
      const i = this.t('i');
      this.line(`${label}: for (let ${i} = 0; ${i} < ${arr}.length; ${i}++) {`);
      this.ind++;
      this.line(`let ${s.pat.js} = ${arr}[${i}];`);
      this.line('try {');
      this.stmts(s.body, null);
      this.line(`} finally { ${arr}[${i}] = ${s.pat.js}; }`);
      this.ind--;
      this.line('}');
      return;
    }
    const { code, pre } = this.capture(() => this.expr(it));
    this.flush(pre);
    const target = this.destructure(s.pat);
    const src = s.await ? `$.aiter(${code})` : `$.iter(${code})`;
    if (target) {
      this.line(`${label}: for ${s.await ? 'await ' : ''}(const ${target} of ${src}) {`);
      body();
    } else {
      const v = this.t('x');
      this.line(`${label}: for ${s.await ? 'await ' : ''}(const ${v} of ${src}) {`);
      this.ind++;
      const vars = new Set();
      const c = this.pat(s.pat, v, vars);
      if (vars.size) this.line(`let ${[...vars].join(', ')};`);
      this.line(`if (!(${c})) continue;`);
      this.ind--;
      body();
    }
    this.line('}');
  }

  // ───────────────────────── patterns ─────────────────────────
  /** JS boolean expression testing `v` against pattern `p`; bindings are assigned inline. */
  pat(p, v, vars, isCatch = false) {
    const bind = (js, expr) => { vars.add(js); return `((${js} = ${expr}), true)`; };
    const all = (parts) => (parts.length ? parts.join(' && ') : 'true');
    switch (p.k) {
      case 'PWild': return 'true';
      case 'PBind': return bind(p.js, v);
      case 'PLit': return p.value.k === 'None' ? `(${v} === undefined || ${v} === null)` : `$.eq(${v}, ${this.expr(p.value)})`;
      case 'PRange': {
        const parts = [];
        if (p.lo) parts.push(`${v} >= ${this.expr(p.lo)}`);
        if (p.hi) parts.push(`${v} ${p.incl ? '<=' : '<'} ${this.expr(p.hi)}`);
        return `(${all(parts)})`;
      }
      case 'PTuple': return `(Array.isArray(${v}) && ${v}.length === ${p.items.length}${p.items.map((x, i) => ` && ${this.pat(x, `${v}[${i}]`, vars)}`).join('')})`;
      case 'PSlice': {
        const restAt = p.items.findIndex((x) => x.k === 'PRest');
        const parts = [`Array.isArray(${v})`];
        if (restAt === -1) {
          parts.push(`${v}.length === ${p.items.length}`);
          p.items.forEach((x, i) => parts.push(this.pat(x, `${v}[${i}]`, vars)));
        } else {
          const after = p.items.length - restAt - 1;
          parts.push(`${v}.length >= ${p.items.length - 1}`);
          p.items.forEach((x, i) => {
            if (i < restAt) parts.push(this.pat(x, `${v}[${i}]`, vars));
            else if (i > restAt) parts.push(this.pat(x, `${v}[${v}.length - ${p.items.length - i}]`, vars));
          });
          const r = p.items[restAt];
          if (r.js) parts.push(bind(r.js, `${v}.slice(${restAt}, ${v}.length - ${after})`));
        }
        return `(${all(parts)})`;
      }
      case 'PRecord': {
        const name = p.name.split('.').pop();
        const sym = p.sym;
        const parts = [];
        if (sym?.kind === 'variant') parts.push(`$.tag(${v}) === ${JSON.stringify(name)}`);
        else if (sym?.kind === 'type' || sym?.kind === 'error') parts.push(`${v} instanceof ${sym.js}`);
        else parts.push(`$.tag(${v}) === ${JSON.stringify(name)}`);
        for (const f of p.fields) parts.push(this.pat(f.pat, `${v}.${this.fieldJs(sym, f.name)}`, vars));
        return `(${all(parts)})`;
      }
      case 'PCtor': {
        const name = p.name.split('.').pop();
        const sym = p.sym;
        if (name === 'Some') return `(${v} !== undefined && ${v} !== null${p.args[0] ? ` && ${this.pat(p.args[0], v, vars)}` : ''})`;
        if (name === 'Ok') return `($.isOk(${v})${p.args[0] ? ` && ${this.pat(p.args[0], `${v}.value`, vars)}` : ''})`;
        if (name === 'Err') return `($.isErr(${v})${p.args[0] ? ` && ${this.pat(p.args[0], `${v}.error`, vars)}` : ''})`;
        const whole = (test) => {
          if (p.args.length === 1 && p.args[0].k === 'PBind') return `(${test} && ${bind(p.args[0].js, v)})`;
          return `(${test}${p.args.map((a, i) => ` && ${this.pat(a, `${v}[${i}]`, vars)}`).join('')})`;
        };
        if (sym?.kind === 'error' || sym?.kind === 'type') return whole(`${v} instanceof ${sym.js}`);
        if (sym?.kind === 'variant') return `($.tag(${v}) === ${JSON.stringify(name)}${p.args.map((a, i) => ` && ${this.pat(a, `${v}[${i}]`, vars)}`).join('')})`;
        if (sym?.kind === 'jsval' && !p.args.length && !isCatch) return `(${v} instanceof ${sym.js})`; // `x is Date`, `e is RangeError`
        if (sym?.kind === 'const' || sym?.kind === 'var') return `$.eq(${v}, ${sym.js})`;
        if (isCatch) return whole(`$.errName(${v}) === ${JSON.stringify(name)}`);
        return `($.tag(${v}) === ${JSON.stringify(name)}${p.args.map((a, i) => ` && ${this.pat(a, `${v}[${i}]`, vars)}`).join('')})`;
      }
      case 'PType': {
        const test = {
          str: `typeof ${v} === 'string'`, char: `typeof ${v} === 'string'`, bool: `typeof ${v} === 'boolean'`,
          int: `Number.isInteger(${v})`, i32: `Number.isInteger(${v})`, i64: `(typeof ${v} === 'bigint' || Number.isInteger(${v}))`,
          f64: `typeof ${v} === 'number'`, f32: `typeof ${v} === 'number'`, float: `typeof ${v} === 'number'`, num: `typeof ${v} === 'number'`,
          big: `typeof ${v} === 'bigint'`, list: `Array.isArray(${v})`, map: `${v} instanceof Map`, bytes: `${v} instanceof Uint8Array`,
        }[p.type] || (JS_GLOBALS.includes(p.type) ? `${v} instanceof ${p.type}` : `$.tag(${v}) === ${JSON.stringify(p.type)}`);
        return p.js ? `(${test} && ${bind(p.js, v)})` : `(${test})`;
      }
      case 'PRoute': {
        const r = this.t('rt');
        vars.add(r);
        const segs = p.segs.map((s) => (s.param ? ':' : s.rest ? '*' : s.lit));
        const binds = p.segs.filter((s) => s.param).map((s, i) => ` && ${bind(s.js, `${r}[${i}]`)}`).join('');
        return `((${r} = $.route(${v}, ${JSON.stringify(p.method)}, ${JSON.stringify(segs)})) !== undefined${binds})`;
      }
      case 'POr': return `(${p.alts.map((a) => this.pat(a, v, vars)).join(' || ')})`;
      case 'PAs': return `(${this.pat(p.pat, v, vars)} && ${bind(p.js, v)})`;
      default: throw this.err(`cannot compile pattern '${p.k}'`, p);
    }
  }

  /** Condition expression; `is` bindings are declared in the enclosing block (R-20.4). */
  cond(e) {
    return this.expr(e);
  }

  // ───────────────────────── expressions ─────────────────────────
  expr(e) {
    switch (e.k) {
      case 'Num': return numJs(e);
      case 'Str': return this.str(e);
      case 'PStr': return this.pstr(e);
      case 'Bool': return String(e.value);
      case 'None': case 'Unit': return 'undefined';
      case 'Ident': return this.ident(e);
      case 'Member': return this.member(e);
      case 'Index': return `$.idx(${this.expr(e.obj)}, ${this.expr(e.index)})`;
      case 'Call': return this.call(e);
      case 'Prop': return this.prop(e);
      case 'Await': return `(await ${this.expr(e.expr)})`;
      case 'Binary': return this.binary(e);
      case 'Range': return `$.range(${e.lo ? this.expr(e.lo) : 'undefined'}, ${e.hi ? this.expr(e.hi) : 'undefined'}, ${e.incl}${e.step ? `, ${this.expr(e.step)}` : ''})`;
      case 'Logic': return this.logic(e);
      case 'Not': return `!(${this.expr(e.expr)})`;
      case 'Bit': return `(${this.expr(e.left)} ${e.op} ${this.expr(e.right)})`;
      case 'BitNot': return `(~${this.expr(e.expr)})`;
      case 'Neg': return `(-${this.expr(e.expr)})`;
      case 'Tuple': return `$.tuple(${e.items.map((x) => this.expr(x)).join(', ')})`;
      case 'List': return `[${e.items.map((x) => this.expr(x)).join(', ')}]`;
      case 'SetLit': return `new Set([${e.items.map((x) => this.expr(x)).join(', ')}])`;
      case 'MapLit': return `new Map([${e.entries.map((x) => (x.spread ? `...$.entries(${this.expr(x.spread)})` : `[${this.expr(x.key)}, ${this.expr(x.value)}]`)).join(', ')}])`;
      case 'Spread': return `...${this.expr(e.expr)}`;
      case 'Record': return this.record(e);
      case 'Cond': return this.condExpr(e);
      case 'Is': { const vars = new Set(); const v = this.t('i'); vars.add(v); const c = this.pat(e.pat, v, vars); this.line(`let ${[...vars].join(', ')};`); return `((${v} = ${this.expr(e.expr)}), ${c})`; }
      case 'Lambda': return this.lambda(e);
      case 'Proj': return `(($x) => ${e.path.reduce((acc, n) => (/^\d+$/.test(n) ? `${acc}[${n}]` : this.opts.fields.get(n) ? `${acc}.${this.opts.fields.get(n)}` : `$.get(${acc}, ${JSON.stringify(n)})`), '$x')})`;
      case 'FnRef': return this.fnRef(e.expr);
      case 'RaiseExpr': return `$.throwNow(${this.expr(e.value)})`;
      case 'Paren': return `(${this.expr(e.expr)})`;
      case 'Embed': return this.embed(e);
      case 'If': case 'Match': case 'Try': case 'Block': case 'With': case 'Loop': case 'For': return this.blockValue(e);
      default: throw this.err(`cannot compile expression '${e.k}'`, e);
    }
  }

  ident(e) {
    const s = e.sym;
    if (!s) return e.js;
    if (s.kind === 'fn' && s.arity === 0 && !s.local) return `${s.js}()`; // R-9.5 zero-arity call in value position
    if (s.kind === 'error' && s.arity === 0) return s.js;
    return s.js;
  }

  member(e) {
    const obj = e.obj;
    if (/^\d+$/.test(e.name)) return `${this.expr(obj)}[${e.name}]`;
    if (obj.k === 'Ident' && obj.sym) {
      const s = obj.sym;
      if (s.kind === 'mod') {
        if (s.std) return `$.get(${s.js}, ${JSON.stringify(e.name)})`;
        const ex = s.exports?.get(e.name);
        if (ex) return ex.kind === 'fn' && ex.arity === 0 ? `${s.js}.${ex.js}()` : `${s.js}.${ex.js}`;
        return `${s.js}.${e.name}`;
      }
      if (s.kind === 'type' || s.kind === 'jsval' || s.kind === 'error' || s.kind === 'trait') return `${s.js}.${e.name}`;
    }
    const target = this.expr(obj);
    const field = e.field || this.opts.fields.get(e.name);
    if (e.opt) return `$.getOpt(${target}, ${JSON.stringify(field || e.name)})`;
    if (field) return `${target}.${field}`;
    return `$.get(${target}, ${JSON.stringify(e.name)})`;
  }

  fnRef(x) {
    if (x.k === 'Ident') return x.sym?.js || x.js;
    if (x.k === 'Member') {
      if (x.obj.k === 'Ident' && ['mod', 'type', 'jsval'].includes(x.obj.sym?.kind)) return this.member(x).replace(/\(\)$/, '');
      return `$.method(${this.expr(x.obj)}, ${JSON.stringify(x.name)})`;
    }
    return this.expr(x);
  }

  args(e) {
    // `f()` is a call with no arguments (not one `undefined` argument); a pipeline stage keeps its receiver slot.
    if (e.args.length === 1 && e.args[0].k === 'Unit' && e.callee.sym?.kind !== 'stage') return [];
    return e.args.map((a) => this.expr(a));
  }

  call(e) {
    const c = e.callee;
    const info = e.info || {};
    let args = this.args(e);
    let js;
    if (c.k === 'Ident' && c.sym) {
      const s = c.sym;
      if (s.kind === 'fn' && e.named.length && s.params) args = this.placeNamed(args, e.named, s.params);
      else if (e.named.length) args.push(this.namedObj(e.named));
      if (s.kind === 'stage') js = `$.call(${args[0]}, ${JSON.stringify(c.name)}, [${args.slice(1).join(', ')}])`;
      else if (s.kind === 'mod' && info.logCall) js = `${s.js}.info(${args.join(', ')})`;
      else if (s.kind === 'variant') js = `${s.js}(${args.join(', ')})`;
      else if (s.kind === 'error' || s.kind === 'type') js = `new ${s.js}(${args.join(', ')})`;
      else js = `${s.js}(${args.join(', ')})`;
    } else if (c.k === 'Member') {
      if (e.named.length) args.push(this.namedObj(e.named));
      const obj = c.obj;
      if (obj.k === 'Ident' && obj.sym && ['mod', 'type', 'jsval', 'error'].includes(obj.sym.kind)) {
        const s = obj.sym;
        let name = c.name;
        if (s.kind === 'mod' && !s.std) name = s.exports?.get(c.name)?.js || c.name;
        const ctor = info.ctor === 'type' || info.ctor === 'error' ? 'new ' : '';
        js = `${ctor}${s.js}.${name}(${args.join(', ')})`;
      } else {
        js = `$.call(${this.expr(obj)}, ${JSON.stringify(c.name)}, [${args.join(', ')}])`;
      }
    } else {
      if (e.named.length) args.push(this.namedObj(e.named));
      js = `(${this.expr(c)})(${args.join(', ')})`;
    }
    // Calls to erroring functions without `?` produce Ok/Err values (R-25.3).
    if (e.erroring && !this.propagating) return e.async ? `$.resP(${js})` : `$.res(() => ${js})`;
    return js;
  }

  placeNamed(args, named, params) {
    const out = [...args];
    for (const n of named) {
      const i = params.indexOf(n.name);
      if (i === -1) throw this.err(`unknown named argument '${n.name}'`, n.value, 'E117');
      while (out.length < i) out.push('undefined');
      out[i] = this.expr(n.value);
    }
    return out;
  }

  namedObj(named) {
    return `{ ${named.map((n) => `${JSON.stringify(n.name)}: ${this.expr(n.value)}`).join(', ')} }`;
  }

  prop(e) {
    const inner = e.expr;
    const erroring = inner.erroring || (inner.k === 'Await' && inner.expr.erroring);
    const saved = this.propagating;
    this.propagating = true;
    const code = this.expr(inner);
    this.propagating = saved;
    if (erroring) return code;
    return `$.q(${code})`;
  }

  binary(e) {
    const op = e.op;
    if (op === '??') {
      const lErroring = e.left.erroring || (e.left.k === 'Await' && e.left.expr.erroring);
      if (lErroring) {
        const saved = this.propagating;
        this.propagating = true;
        const l = this.expr(e.left);
        this.propagating = saved;
        const { code: r, pre } = this.capture(() => this.expr(e.right));
        const rFn = pre.length ? `() => { ${pre.map((x) => x.trim()).join(' ')} return ${r}; }` : `() => ${r}`;
        return e.left.async || e.left.k === 'Await' ? `(await $.coP(async () => ${l}, ${rFn}))` : `$.co(() => ${l}, ${rFn})`;
      }
      const l = this.expr(e.left);
      const { code: r, pre } = this.capture(() => this.expr(e.right));
      if (!pre.length) return `$.orElse(${l}, () => ${r})`;
      const v = this.t('c');
      this.line(`let ${v} = ${l};`);
      this.line(`if (${v} === undefined || ${v} === null || $.isErr(${v})) {`);
      this.ind++; this.flush(pre); this.line(`${v} = ${r};`); this.ind--;
      this.line(`} else ${v} = $.unwrapOk(${v});`);
      return v;
    }
    let l = this.expr(e.left);
    let r = this.expr(e.right);
    // A BigInt literal on one side promotes a plain integer literal on the other (2**64big).
    const isBig = (x) => x.k === 'Num' && typeof x.value === 'bigint';
    const isInt = (x) => x.k === 'Num' && typeof x.value === 'number' && Number.isInteger(x.value);
    if (isBig(e.right) && isInt(e.left)) l = `${e.left.value}n`;
    if (isBig(e.left) && isInt(e.right)) r = `${e.right.value}n`;
    switch (op) {
      case '==': return `$.eq(${l}, ${r})`;
      case '!=': return `!$.eq(${l}, ${r})`;
      case '//': return `$.fdiv(${l}, ${r})`;
      case '*': return isSeqLit(e.left) || isSeqLit(e.right) ? `$.mul(${l}, ${r})` : `(${l} * ${r})`;
      case '+': return isSeqLit(e.left) || isSeqLit(e.right) ? `$.add(${l}, ${r})` : `(${l} + ${r})`;
      default: return `(${l} ${JS_BINARY[op]} ${r})`;
    }
  }

  logic(e) {
    const l = this.expr(e.left);
    const { code: r, pre } = this.capture(() => this.expr(e.right));
    if (!pre.length) return `(${l} ${e.op} ${r})`;
    const v = this.t('l');
    this.line(`let ${v} = ${l};`);
    this.line(`if (${e.op === '&&' ? v : `!${v}`}) {`);
    this.ind++; this.flush(pre); this.line(`${v} = ${r};`); this.ind--;
    this.line('}');
    return v;
  }

  condExpr(e) {
    const c = this.expr(e.cond);
    const a = this.capture(() => this.expr(e.a));
    const b = this.capture(() => this.expr(e.b));
    if (!a.pre.length && !b.pre.length) return `(${c} ? ${a.code} : ${b.code})`;
    const v = this.t('c');
    this.line(`let ${v};`);
    this.line(`if (${c}) {`); this.ind++; this.flush(a.pre); this.line(`${v} = ${a.code};`); this.ind--;
    this.line('} else {'); this.ind++; this.flush(b.pre); this.line(`${v} = ${b.code};`); this.ind--;
    this.line('}');
    return v;
  }

  record(e) {
    const s = e.sym;
    const fields = e.fields.map((f) => `${JSON.stringify(this.fieldJs(s, f.name))}: ${this.expr(f.value)}`);
    if (e.spread) fields.unshift(`...${this.expr(e.spread)}`);
    const obj = `{ ${fields.join(', ')} }`;
    if (!s) throw this.err(`unknown type '${e.type}' in record literal`, e, 'E201');
    if (s.kind === 'variant') return `${s.js}(${obj})`;
    return `new ${s.js}($.lit(${obj}))`;
  }

  lambda(e) {
    const { list } = this.params(e.params.map((p) => ({ pat: p })));
    const params = e.variadic && e.params.length ? list.replace(/([^,]+)$/, (m) => `...${m.trim()}`) : list;
    const head = `${e.async ? 'async ' : ''}(${params}) =>`;
    if (e.block) {
      const cap = this.capture(() => {
        this.ind++;
        this.inFn++;
        const saved = this.loops; this.loops = [];
        this.withOptQ(e.usesOptQ, () => this.stmts(e.block, (c) => this.line(`return ${c};`)));
        this.loops = saved;
        this.inFn--;
        this.ind--;
      });
      return `${head} {\n${cap.pre.join('\n')}\n${'  '.repeat(this.ind)}}`;
    }
    const cap = this.capture(() => { this.ind++; const c = this.expr(e.body); this.ind--; return c; });
    if (!cap.pre.length && !e.usesOptQ) return `(${head} ${cap.code})`;
    const inner = [...cap.pre, `${'  '.repeat(this.ind + 1)}return ${cap.code};`];
    if (e.usesOptQ) return `(${head} { try {\n${inner.join('\n')}\n${'  '.repeat(this.ind)}} catch ($e) { if ($e === $.NONE) return undefined; throw $e; } })`;
    return `(${head} {\n${inner.join('\n')}\n${'  '.repeat(this.ind)}})`;
  }

  str(e) {
    let out = '`';
    for (const p of e.parts) {
      if (typeof p === 'string') out += p.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${').replace(/\r/g, '\\r'); // a raw CR in a template literal reads back as LF
      else {
        const v = this.expr(p.expr);
        const shown = p.fmt !== null && p.fmt !== undefined ? `$.fmt(${v}, ${JSON.stringify(p.fmt)})` : `$.show(${v})`;
        out += p.dbg ? `${p.code.replace(/`/g, '\\`')}=\${${shown}}` : `\${${shown}}`;
      }
    }
    return out + '`';
  }

  pstr(e) {
    const text = e.text !== null ? JSON.stringify(e.text) : this.str(e.str);
    switch (e.prefix) {
      case 're': {
        try { new RegExp(e.text ?? '', e.flags); } catch (err) { throw this.err(`invalid regular expression: ${err.message}`, e, 'E305'); }
        return `new RegExp(${text}, ${JSON.stringify(e.flags)})`;
      }
      case 'b': return `$.bytes(${text})`;
      case 'c': return `(${text} + '\\0')`;
      default: return `$.strMacro(${JSON.stringify(e.prefix)}, ${text})`;
    }
  }

  embed(e) {
    const rel = e.path.parts?.join('') ?? '';
    const file = path.resolve(this.opts.dir, rel);
    if (!fs.existsSync(file)) throw this.err(`$embed: file not found: ${rel}`, e, 'E903');
    return JSON.stringify(fs.readFileSync(file, 'utf8'));
  }
}

const CHECKED_KINDS = {
  str: 'str', num: 'num', int: 'int', float: 'num', bool: 'bool', list: 'list', map: 'map', set: 'set', fn: 'fn', date: 'date', regex: 'regex',
  i8: 'int', i16: 'int', i32: 'int', i64: 'int', u8: 'int', u16: 'int', u32: 'int', u64: 'int', f32: 'num', f64: 'num',
};

function isBlockExpr(e) {
  return ['If', 'Match', 'Try', 'Block', 'With', 'Loop', 'For'].includes(e.k) && (e.asExpr || e.k === 'Block' || e.k === 'With');
}

function isSeqLit(e) {
  return e.k === 'List' || e.k === 'Str' || e.k === 'Tuple';
}

function numJs(e) {
  if (typeof e.value === 'bigint') return `${e.value}n`;
  if (e.kind === 'num' && !e.suffix) return e.text.replace(/_/g, '');
  return String(e.value);
}

function safeLabel(l) {
  return `L_${l}`;
}

function defaultJs(text) {
  if (/^-?\d[\d_]*(\.\d+)?$/.test(text)) return text.replace(/_/g, '');
  if (text === 'true' || text === 'false') return text;
  if (text === 'none') return 'undefined';
  if (/^".*"?$/.test(text)) return JSON.stringify(text.replace(/^"|"$/g, ''));
  return JSON.stringify(text);
}
